modLoader="javafml"
loaderVersion="[46,)"
license="GNU General Public License 3 (GPLv3)"

[[mods]]
modId="armoryofdestiny"
version="1.22"
displayName="§6§nArmory of Destiny§r"
authors="Destiny"
logoFile="assets/armoryofdestiny/textures/misc/mod_logo.png"
description='''§oArmory of Destiny is a mod that adds various weapons, both fully unique or from popular sources, ranging from swords, to hammers, to even throwing knife fans.
\nAll weapons have interesting in-depth mechanics and high-quality assets, and in the future this mod is planned to not be limited to weapons only, but also artifacts, armors and more!§r
\n \n§4Forge your own destiny.§r
\nMod page: https://curseforge.com/minecraft/mc-mods/armory-of-destiny'''

[[dependencies.armoryofdestiny]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.armoryofdestiny]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.armoryofdestiny]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4.9, )"
    ordering="NONE"
    side="BOTH"